### PR TITLE
Adding class notes about K Means and Clustering from lecture on 2/12

### PR DESCRIPTION
**Pull request by nshalash**

### CODE REVIEW

**Comment by nshalash** [comment]
@gallettilance when I tried typing "git rebase -i master" it said that I had unstaged changes I need to commit, so now I accidentally added 3 commits to the PR. When I tried rebasing again it said "hint: Waiting for your editor to close the file... code --wait: code: command not found
error: There was a problem with the editor 'code --wait'." Not sure how to fix this so I can squash the commits and delete the older version of the pdf.

**Comment by gallettilance** [comment]
@nshalash 
1. You should change your git config to specify a different default editor. In [this stackoverflow answer](https://stackoverflow.com/questions/10564/how-can-i-set-up-an-editor-to-work-with-git-on-windows) you will see that you should specify the direct path to VScode (i.e. "C:/Program Files/..." - you need to figure out what that path is) in the `git config --global core.editor` command.
2. `git rebase -i master` will not work since you are currently working on the master branch... Next time you should create a new branch before making changes. For now, you can do `git rebase -i upstream/master` or `git rebase -i <hash-of-the-commit-that-comes-before-your-commits>` (to get the commit you can do `git log` and copy that commit id.

**Comment by nshalash** [comment]
@gallettilance Thank you so much! I think it worked now. Did I do this correctly?

**Comment by gallettilance** [comment]
closing in favor of #106

**Pull request closed without merging**
